# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Select Xcode 14.2
      run: sudo xcode-select -s /Applications/Xcode_14.2.app

    - uses: swift-actions/setup-swift@v1

      # DerivedData Cache
    - uses: actions/cache@v3
      name: Cache Derived Data
      with:
        path: |
          ~/Library/Developer/Xcode/DerivedData/SwiftyJS-*/Build
          ~/Library/Developer/Xcode/DerivedData/SwiftyJS-*/SourcePackages
        key: ${{ runner.os }}-derivedData-cache-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-derivedData-cache-
          
    - name: Avoid inode changes for DerivedData
      run: defaults write com.apple.dt.XCBuild IgnoreFileSystemDeviceInodeChanges -bool YES

      # SPM Packages Cache
    - uses: actions/cache@v3
      name: Cache SPM Packages
      with:
        path: /Users/runner/Library/Developer/Xcode/DerivedData/**/SourcePackages/checkouts
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-

    - name: Build
      run: swift build -v
      
    - name: Run tests
      run: swift test -v
